{
  env: {
    STEDSNAVN_DB_JDBC_URL: '<STEDSNAVN_DB_JDBC_URL>',
    STEDSNAVN_DB_USERNAME_SECRET_NAME: '<STEDSNAVN_DB_USERNAME_SECRET>',
    STEDSNAVN_DB_PASSWORD_SECRET_NAME: '<STEDSNAVN_DB_PASSWORD_SECRET>',
    STEDSNAVN_OLD_DB_USERNAME_SECRET_NAME: '<STEDSNAVN_OLD_DB_USERNAME_SECRET>',
    STEDSNAVN_OLD_DB_PASSWORD_SECRET_NAME: '<STEDSNAVN_OLD_DB_PASSWORD_SECRET>',
    STEDSNAVN_HIST_DB_USERNAME_SECRET_NAME: '<STEDSNAVN_HIST_DB_USERNAME_SECRET>',
    STEDSNAVN_HIST_DB_PASSWORD_SECRET_NAME: '<STEDSNAVN_HIST_DB_PASSWORD_SECRET>',

    STEDSNAVN_USERS_DB_JDBC_URL: '<STEDSNAVN_USERS_DB_JDBC_URL>',
    STEDSNAVN_USERS_DB_USERNAME_SECRET_NAME: '<STEDSNAVN_USERS_DB_USERNAME_SECRET>',
    STEDSNAVN_USERS_DB_PASSWORD_SECRET_NAME: '<STEDSNAVN_USERS_DB_PASSWORD_SECRET>',

    STEDSNAVN_MATRIKKEL_URL: '<MATRIKKEL_API_URL>',
    STEDSNAVN_MATRIKKEL_USERNAME_SECRET_NAME: '<STEDSNAVN_MATRIKKEL_USERNAME_SECRET>',
    STEDSNAVN_MATRIKKEL_PASSWORD_SECRET_NAME: '<STEDSNAVN_MATRIKKEL_PASSWORD_SECRET>',

    STEDSNAVN_EPOST_CLIENTID_SECRET_NAME: '<STEDSNAVN_EPOST_CLIENTID_SECRET>',
    STEDSNAVN_EPOST_SECRETID_SECRET_NAME: '<STEDSNAVN_EPOST_SECRETID_SECRET>',
    STEDSNAVN_EPOST_TENANTID_SECRET_NAME: '<STEDSNAVN_EPOST_TENANTID_SECRET>',
    STEDSNAVN_EPOST_USERID_SECRET_NAME: '<STEDSNAVN_EPOST_USERID_SECRET>',

    STEDSNAVN_DEPLOYMENT_ENVIRONMENT: 'Betatest',
    STEDSNAVN_SYSTEMNAVN: 'Betatest',

    STEDSNAVN_LUCENE_DIRECTORY: '/tmp/lucene',
  },
  common: {
    config: {
      STEDSNAVN_LUCENE_DIRECTORY: $.env.STEDSNAVN_LUCENE_DIRECTORY,
      STEDSNAVN_DB_JDBC_URL: $.env.STEDSNAVN_DB_JDBC_URL,
      STEDSNAVN_USERS_DB_JDBC_URL: $.env.STEDSNAVN_USERS_DB_JDBC_URL,
      STEDSNAVN_SERVER_PORT: '443',

      STEDSNAVN_SYSTEMNAVN: $.env.STEDSNAVN_SYSTEMNAVN,
      STEDSNAVN_DEPLOYMENT_ENVIRONMENT: $.env.STEDSNAVN_DEPLOYMENT_ENVIRONMENT,

      STEDSNAVN_SHUTDOWN_TIMEOUT_SECONDS: '5',
    },
    fileshare: {
      lucene: {
        name: 'ssr-beta-lucene',
        path: '/tmp/lucene',
      },
    },
    secrets: {
      STEDSNAVN_DB_USERNAME: $.env.STEDSNAVN_DB_USERNAME_SECRET_NAME,
      STEDSNAVN_DB_PASSWORD: $.env.STEDSNAVN_DB_PASSWORD_SECRET_NAME,
      STEDSNAVN_OLD_DB_USERNAME: $.env.STEDSNAVN_OLD_DB_USERNAME_SECRET_NAME,
      STEDSNAVN_OLD_DB_PASSWORD: $.env.STEDSNAVN_OLD_DB_PASSWORD_SECRET_NAME,
      STEDSNAVN_HIST_DB_USERNAME: $.env.STEDSNAVN_HIST_DB_USERNAME_SECRET_NAME,
      STEDSNAVN_HIST_DB_PASSWORD: $.env.STEDSNAVN_HIST_DB_PASSWORD_SECRET_NAME,
      STEDSNAVN_USERS_DB_USERNAME: $.env.STEDSNAVN_USERS_DB_USERNAME_SECRET_NAME,
      STEDSNAVN_USERS_DB_PASSWORD: $.env.STEDSNAVN_USERS_DB_PASSWORD_SECRET_NAME,

      STEDSNAVN_EPOST_CLIENTID: $.env.STEDSNAVN_EPOST_CLIENTID_SECRET_NAME,
      STEDSNAVN_EPOST_SECRETID: $.env.STEDSNAVN_EPOST_SECRETID_SECRET_NAME,
      STEDSNAVN_EPOST_TENANTID: $.env.STEDSNAVN_EPOST_TENANTID_SECRET_NAME,
      STEDSNAVN_EPOST_USERID: $.env.STEDSNAVN_EPOST_USERID_SECRET_NAME,
    },
  },
  stedsnavnear: {
    config: $.common.config {
      STEDSNAVN_SERVER_IP: '<STEDSNAVN_SERVER_IP>',
      STEDSNAVN_SERVER_URL: 'https://' + $.stedsnavnear.config.STEDSNAVN_SERVER_IP,
      STEDSNAVN_MATRIKKEL_URL: $.env.STEDSNAVN_MATRIKKEL_URL,
    },
    secrets: $.common.secrets {
      STEDSNAVN_MATRIKKEL_USERNAME: $.env.STEDSNAVN_MATRIKKEL_USERNAME_SECRET_NAME,
      STEDSNAVN_MATRIKKEL_PASSWORD: $.env.STEDSNAVN_MATRIKKEL_PASSWORD_SECRET_NAME,
    },
  },

  stedsnavnjobbserver: {
    config: $.common.config {
      STEDSNAVN_SERVER_IP: '<STEDSNAVN_JOBBSERVER_IP>',
      STEDSNAVN_SERVER_URL: 'https://' + $.stedsnavnjobbserver.config.STEDSNAVN_SERVER_IP,
    },
    secrets: $.common.secrets,
  },

}
