apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: gsm
spec:
  provider:
    gcpsm:
      projectID: skvis-dev-5aa6
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: streamlit-secrets
spec:
  secretStoreRef:
    kind: SecretStore
    name: gsm
  target:
    name: streamlit-secrets
  data:
    - secretKey: secrets.toml
      remoteRef:
        key: streamlit-secrets
        metadataPolicy: None
