apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: komreg-kubernetes-secrets
spec:
  data:
    - remoteRef:
        key: db_matrikkel_jdbc_url
        metadataPolicy: None
      secretKey: DB_MATRIKKEL_JDBC_URL
    - remoteRef:
        key: db_matrikkel_backing_username
        metadataPolicy: None
      secretKey: DB_MATRIKKEL_BACKING_USERNAME
    - remoteRef:
        key: db_matrikkel_backing_password
        metadataPolicy: None
      secretKey: DB_MATRIKKEL_BACKING_PASSWORD
    - remoteRef:
        key: db_matrikkel_mottaker1_username
        metadataPolicy: None
      secretKey: DB_MATRIKKEL_MOTTAKER1_USERNAME
    - remoteRef:
        key: db_matrikkel_mottaker1_password
        metadataPolicy: None
      secretKey: DB_MATRIKKEL_MOTTAKER1_PASSWORD
    - remoteRef:
        key: db_matrikkel_mottaker2_username
        metadataPolicy: None
      secretKey: DB_MATRIKKEL_MOTTAKER2_USERNAME
    - remoteRef:
        key: db_matrikkel_mottaker2_password
        metadataPolicy: None
      secretKey: DB_MATRIKKEL_MOTTAKER2_PASSWORD
    - remoteRef:
        key: db_komreg_jdbc_url
        metadataPolicy: None
      secretKey: DB_KOMREG_JDBC_URL
    - remoteRef:
        key: db_komreg_username
        metadataPolicy: None
      secretKey: DB_KOMREG_USERNAME
    - remoteRef:
        key: db_komreg_password
        metadataPolicy: None
      secretKey: DB_KOMREG_PASSWORD
    - remoteRef:
        key: db_matrikkel_system_username
        metadataPolicy: None
      secretKey: DB_MATRIKKEL_SYSTEM_USERNAME
    - remoteRef:
        key: db_matrikkel_system_password
        metadataPolicy: None
      secretKey: DB_MATRIKKEL_SYSTEM_PASSWORD


  refreshInterval: 1h

  secretStoreRef:
    kind: SecretStore
    name: gsm

  target:
    name: komreg-kubernetes-secrets
