apiVersion: skiperator.kartverket.no/v1alpha1  # Change API version
kind: SKIPJob
metadata:
  name: test-job
  namespace: test
  labels:
    version: "v1alpha1"
spec:
  container:
    image: busybox:latest
    command: ["echo", "Using v1alpha1"]
    cron:
      schedule: "*/10 * * *"
      suspend: true
  job:
    ttlSecondsAfterFinished: 100